CREATE DATABASE twinscroll;

USE twinscroll;

CREATE TABLE identities (
	id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	token CHAR(32) UNIQUE NOT NULL,
	userid TEXT NOT NULL,
	ip TEXT,
	useragent TEXT,
	created DATETIME NOT NULL,
	modified DATETIME NOT NULL
);
